# Generated by Django 3.2.18 on 2023-05-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='num',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='prise_per_item',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_prise',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.order', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.product', verbose_name='Блюдо'),
        ),
    ]
