# Generated by Django 3.2.18 on 2023-05-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20230512_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_prise',
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.order', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.product', verbose_name='Блюдо'),
        ),
    ]
