# Generated by Django 3.2.18 on 2023-05-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_basket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_prise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
